name: SQS Automation Docker Build and Push

permissions:
  security-events: write
  contents: read

on:
  push: # There's no "merge" event so the best solution I found was trigger on push to main 
    branches:
      - main
  workflow_dispatch:      # Allows manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    environment: dev
    
    steps:
      - uses: actions/checkout@v4 #checkout repository
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ vars.VERSION }}
          push: false 

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ vars.VERSION }}
          push: true 